### ISSUE TITLE
{{console.log()}} fails in firefox

### ISSUE THREAD

**Issue by enjalot** [derbyjs/derby-standalone#4]
repro:
http://codepen.io/enjalot/pen/azKrZG?editors=100

**Comment by hflw** [comment]
I loaded up the example in FF and this is the error that's being thrown: "TypeError: 'console' getter called on an object that does not implement interface Window."

**Comment by hflw** [comment]
Looks like it's working in the newer version of derby: http://codepen.io/anon/pen/yyqYzQ?editors=100

**Comment by enjalot** [comment]
:boom: thanks!
